// Generated by build.js from "Hero Track Star.dc.html". Do not edit by hand.
// The class body below is copied verbatim from the design document's
// data-dc-script block; only the surrounding wiring is added.
(function () {
  'use strict';

  // The design runtime's base class. Nothing in this component uses it, so an
  // empty base is enough to let the class body run unmodified.
  class DCLogic {}

  class Component extends DCLogic {
    componentDidMount() {
      const hots = Array.prototype.slice.call(document.querySelectorAll('[data-stars-hot]'));
      if (hots.length) {
        const off = 'radial-gradient(circle 150px at -300px -300px, #000 0%, rgba(0,0,0,0.35) 55%, transparent 78%)';
        hots.forEach(el => { el.style.maskImage = off; el.style.webkitMaskImage = off; });
        this._move = ev => {
          hots.forEach(el => {
            const b = el.getBoundingClientRect();
            const g = 'radial-gradient(circle 150px at ' + (ev.clientX - b.left).toFixed(0) + 'px ' + (ev.clientY - b.top).toFixed(0) + 'px, #000 0%, rgba(0,0,0,0.35) 55%, transparent 78%)';
            el.style.maskImage = g;
            el.style.webkitMaskImage = g;
          });
        };
        window.addEventListener('pointermove', this._move, { passive: true });
      }
      const track = document.querySelector('[data-track]');
      const wrap = document.querySelector('[data-marquee]');
      const cards = Array.prototype.slice.call(document.querySelectorAll('[data-cover]'));
      const m = { gap: 0, w: 0, step: 0, period: 0, base: 0, cx: 0, reach: 420, h: 0 };
      const measure = () => {
        if (!track || !wrap || !cards.length) return;
        m.gap = parseFloat(getComputedStyle(track).columnGap) || 0;
        m.w = cards[0].offsetWidth;
        m.step = m.w + m.gap;
        m.period = cards.length / 2 * m.step;
        const wr = wrap.getBoundingClientRect();
        m.base = wr.left + track.offsetLeft;
        m.cx = wr.width / 2;
        m.reach = Math.max(wr.width * 0.5, 420);
        m.h = wr.height;
      };
      measure();
      this._resize = () => measure();
      window.addEventListener('resize', this._resize);
      if (wrap) {
        const layer = document.createElement('div');
        layer.setAttribute('style', 'position:absolute;inset:0;pointer-events:none;z-index:5;overflow:hidden');
        wrap.appendChild(layer);
        let lastSpark = 0;
        this._spark = ev => {
          const now = performance.now();
          if (now - lastSpark < 90) return;
          lastSpark = now;
          const b = wrap.getBoundingClientRect();
          const px = ev.clientX - b.left, py = ev.clientY - b.top;
          if (px < 0 || py < 0 || px > b.width || py > b.height) return;
          const s = document.createElement('span');
          const size = 13 + Math.random() * 14;
          const dur = 1500 + Math.random() * 900;
          const tone = 0.58 + Math.random() * 0.26;
          const hue = 38 + Math.random() * 16;
          s.textContent = '★';
          s.setAttribute('style', 'position:absolute;left:' + (px + (Math.random() - 0.5) * 40).toFixed(1) + 'px;top:' + (py + (Math.random() - 0.5) * 26).toFixed(1) + 'px;font-size:' + size.toFixed(1) + 'px;line-height:1;color:oklch(' + (tone + 0.1).toFixed(2) + ' 0.17 ' + hue.toFixed(0) + ');text-shadow:0 0 6px oklch(0.85 0.13 45 / 0.9), 0 0 16px oklch(0.72 0.19 45 / 0.75), 0 0 34px oklch(0.68 0.2 42 / 0.5);will-change:transform,opacity;animation:ts-star-fall ' + dur.toFixed(0) + 'ms cubic-bezier(0.22,0.7,0.24,1) forwards');
          s.addEventListener('animationend', () => s.remove());
          layer.appendChild(s);
        };
        wrap.addEventListener('pointermove', this._spark, { passive: true });
        this._sparkHost = wrap;
        this._slowT = 0;
        this._enter = () => { this._slow = true; };
        this._leave = () => { this._slow = false; };
        cards.forEach(c => {
          c.addEventListener('pointerenter', this._enter);
          c.addEventListener('pointerleave', this._leave);
        });
      }
      const reveals = Array.prototype.slice.call(document.querySelectorAll('[data-reveal],[data-pop]'));
      if (reveals.length && window.IntersectionObserver) {
        reveals.forEach(el => { el.style.opacity = '0'; });
        const io = new IntersectionObserver(entries => {
          entries.forEach(entry => {
            if (!entry.isIntersecting) return;
            const el = entry.target;
            const group = el.hasAttribute('data-pop') ? el.parentElement.children : null;
            const idx = group ? Array.prototype.indexOf.call(group, el) : reveals.indexOf(el);
            const delay = (el.hasAttribute('data-pop') ? 0.12 + idx * 0.09 : idx * 0.1).toFixed(2);
            el.style.opacity = '';
            el.style.animation = (el.hasAttribute('data-pop') ? 'ts-pop 0.75s' : 'ts-rise 0.9s') + ' cubic-bezier(0.16,1,0.3,1) ' + delay + 's both';
            if (el.hasAttribute('data-pulse')) {
              el.addEventListener('animationend', () => {
                el.style.animation = 'ts-pulse 2.6s ease-in-out 0.4s infinite';
              }, { once: true });
            }
            io.unobserve(el);
          });
        }, { threshold: 0.25 });
        reveals.forEach(el => io.observe(el));
        this._io = io;
      }
      const faces = Array.prototype.slice.call(document.querySelectorAll('[data-face]'));
      if (faces.length) {
        const pool = ['p1','p2','p3','p4','p5','p6','p7','p8','p9'];
        let cursor = faces.length;
        let slot = 0;
        this._faceTimer = setInterval(() => {
          if (document.hidden) return;
          const img = faces[slot % faces.length];
          slot++;
          const next = './people/' + pool[cursor % pool.length] + '.png';
          cursor++;
          const circle = img.parentElement;
          if (!circle || circle.querySelector('[data-face-in]')) return;
          circle.style.position = 'relative';
          const over = document.createElement('img');
          over.setAttribute('data-face-in', '');
          over.setAttribute('alt', '');
          over.setAttribute('style', 'position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block;opacity:0;transform:scale(1.06);transition:opacity 900ms cubic-bezier(0.4,0,0.2,1),transform 900ms cubic-bezier(0.4,0,0.2,1)');
          over.src = next;
          const start = () => {
            circle.appendChild(over);
            requestAnimationFrame(() => {
              over.style.opacity = '1';
              over.style.transform = 'scale(1)';
            });
            setTimeout(() => {
              img.src = next;
              over.remove();
            }, 980);
          };
          if (over.complete) start(); else over.addEventListener('load', start, { once: true });
        }, 1900);
      }
      this._shineCleanup = [];
      document.querySelectorAll('[data-shine]').forEach(card => {
        const enter = () => {
          const g = document.createElement('span');
          g.setAttribute('style', 'position:absolute;left:-45%;top:-45%;width:190%;height:190%;pointer-events:none;z-index:3;background:linear-gradient(122deg, transparent 30%, rgb(255 255 255 / 0.015) 40%, rgb(255 255 255 / 0.055) 47%, rgb(255 255 255 / 0.13) 50%, rgb(255 255 255 / 0.055) 53%, rgb(255 255 255 / 0.015) 60%, transparent 70%);will-change:transform,opacity;animation:ts-sweep 1450ms cubic-bezier(0.16,0.85,0.2,1) forwards');
          g.addEventListener('animationend', () => g.remove());
          card.appendChild(g);
        };
        card.addEventListener('pointerenter', enter);
        this._shineCleanup.push(() => card.removeEventListener('pointerenter', enter));
      });
      this._previewCleanup = [];
      document.querySelectorAll('[data-video]').forEach(box => {
        const link = box.parentElement.querySelector('a[href*="youtube.com/watch"]');
        const id = link ? (link.getAttribute('href').split('v=')[1] || '').split('&')[0] : '';
        if (!id) return;
        const frames = ['hq1', 'hq2', 'hq3', 'mqdefault'];
        let layer = null, timer = null, cycle = null, step = 0;
        const enter = () => {
          if (layer || timer) return;
          timer = setTimeout(() => {
            timer = null;
            step = 0;
            layer = document.createElement('img');
            layer.setAttribute('alt', '');
            layer.setAttribute('style', 'position:absolute;inset:0;width:100%;height:100%;object-fit:cover;pointer-events:none;opacity:0;transition:opacity 0.35s ease');
            layer.src = 'https://i.ytimg.com/vi/' + id + '/' + frames[0] + '.jpg';
            box.appendChild(layer);
            requestAnimationFrame(() => { if (layer) layer.style.opacity = '1'; });
            cycle = setInterval(() => {
              if (!layer) return;
              step = (step + 1) % frames.length;
              layer.src = 'https://i.ytimg.com/vi/' + id + '/' + frames[step] + '.jpg';
            }, 850);
          }, 200);
        };
        const leave = () => {
          if (timer) { clearTimeout(timer); timer = null; }
          if (cycle) { clearInterval(cycle); cycle = null; }
          if (layer) { layer.remove(); layer = null; }
        };
        box.parentElement.addEventListener('pointerenter', enter);
        box.parentElement.addEventListener('pointerleave', leave);
        this._previewCleanup.push(() => {
          box.parentElement.removeEventListener('pointerenter', enter);
          box.parentElement.removeEventListener('pointerleave', leave);
          leave();
        });
      });
      let x = 0, last = performance.now(), t0 = last;
      const tick = () => {
        const now = performance.now();
        const dt = Math.min((now - last) / 1000, 0.05);
        last = now;
        if (m.period <= 0) measure();
        const target = Math.min(window.scrollY / Math.max(window.innerHeight * 0.8, 1), 1);
        this._bend = (this._bend || 0) + (target - (this._bend || 0)) * Math.min(dt * 6, 1);
        if (!document.hidden && m.period > 0) {
          const cruise = m.period / 31;
          this._slowT = (this._slowT || 0) + ((this._slow ? 1 : 0) - (this._slowT || 0)) * Math.min(dt * 5, 1);
          const v = (cruise + (m.period * 1.05 - cruise) * Math.exp(-(now - t0) / 1350)) * (1 - 0.72 * this._slowT);
          x = (x - v * dt) % m.period;
          track.style.transform = 'translateX(' + x.toFixed(2) + 'px)';
          for (let i = 0; i < cards.length; i++) {
            const el = cards[i];
            const centre = m.base + x + i * m.step + m.w / 2;
            const dx = (centre - (m.base + m.cx)) / m.reach;
            const d = Math.min(Math.abs(dx), 1);
            const ee = d * d * (3 - 2 * d);
            const near = 1 - ee;
            const pop = near * near;
            const bend = this._bend || 0;
            const arc = bend * 46 * Math.min(dx * dx, 1);
            const swing = bend * 6.5 * Math.max(-1, Math.min(dx, 1));
            el.style.opacity = Math.max(0, 1 - bend * (0.45 + 0.85 * Math.min(dx * dx, 1))).toFixed(3);
            el.style.transform = 'translateY(' + (-Math.min(14, m.h * 0.05) * pop + arc).toFixed(2) + 'px) rotate(' + (1.3 * Math.sign(dx) * ee + swing).toFixed(2) + 'deg) scale(' + (1 - 0.09 * ee - bend * 0.04).toFixed(4) + ')';
            el.firstElementChild.style.transform = 'translateY(' + (3 * ee).toFixed(2) + 'px)';
            const art = el.lastElementChild;
            art.style.opacity = (0.72 + 0.28 * near).toFixed(3);
            art.style.filter = 'saturate(' + (0.72 + 0.28 * near).toFixed(3) + ') brightness(' + (0.82 + 0.18 * near).toFixed(3) + ') blur(' + (0.6 * ee * ee).toFixed(2) + 'px)';
            art.style.boxShadow = near > 0.05 ? '0 ' + (8 + 16 * near).toFixed(0) + 'px ' + (18 + 30 * near).toFixed(0) + 'px rgb(0 0 0 / ' + (0.38 * near).toFixed(2) + ')' : 'none';
          }
        }
        this._raf = requestAnimationFrame(tick);
      };
      this._raf = requestAnimationFrame(tick);
    }
    componentWillUnmount() {
      cancelAnimationFrame(this._raf);
      if (this._move) window.removeEventListener('pointermove', this._move);
      if (this._resize) window.removeEventListener('resize', this._resize);
      if (this._spark && this._sparkHost) this._sparkHost.removeEventListener('pointermove', this._spark);
      if (this._previewCleanup) this._previewCleanup.forEach(fn => fn());
      if (this._shineCleanup) this._shineCleanup.forEach(fn => fn());
      if (this._io) this._io.disconnect();
      if (this._faceTimer) clearInterval(this._faceTimer);
      if (this._enter) document.querySelectorAll('[data-cover]').forEach(c => {
        c.removeEventListener('pointerenter', this._enter);
        c.removeEventListener('pointerleave', this._leave);
      });
    }
    renderVals() {
      const arrow = () => document.querySelector('[data-cta-arrow]');
      const palettes = {
        dark: { bg: '#0a0a0a', fg: '#f2efea', muted: '#c9c5be', dim: '#8b8781', line: '#403d39', stroke: '#4a4744', art: '#141312', chip: 'rgb(255 255 255 / 0.06)', 'chip-hover': 'rgb(255 255 255 / 0.13)', 'scrim-a': 'rgb(10 10 10 / 0.88)', 'scrim-b': 'rgb(10 10 10 / 0.42)' },
        light: { bg: '#f3f0ea', fg: '#16130f', muted: '#514c45', dim: '#7a746b', line: '#d3cdc2', stroke: '#bdb6aa', art: '#e5e0d6', chip: 'rgb(22 19 15 / 0.08)', 'chip-hover': 'rgb(22 19 15 / 0.16)', 'scrim-a': 'rgb(243 240 234 / 0.9)', 'scrim-b': 'rgb(243 240 234 / 0.45)' }
      };
      const setTheme = light => {
        const p = palettes[light ? 'light' : 'dark'];
        const stars = document.querySelector('[data-stars]');
        const shells = [stars && stars.parentElement, ...document.querySelectorAll('[data-shell]')].filter(Boolean);
        shells.forEach(s => Object.keys(p).forEach(k => s.style.setProperty('--' + k, p[k])));
        document.querySelectorAll('[data-stars],[data-stars-hot]').forEach(el => { el.style.filter = light ? 'invert(1)' : 'none'; });
        const moon = document.querySelector('[data-icon-moon]');
        const sun = document.querySelector('[data-icon-sun]');
        if (moon) moon.style.display = light ? 'none' : 'block';
        if (sun) sun.style.display = light ? 'block' : 'none';
        this._light = light;
      };
      return {
        toggleTheme: () => setTheme(!this._light),
        ctaIn: () => {
          const a = arrow();
          if (a) {
            a.style.animation = 'none';
            void a.offsetWidth;
            a.style.animation = 'ts-fly 0.62s cubic-bezier(0.4,0,0.2,1) 1';
          }
        },
        ctaOut: () => {
          const a = arrow();
          if (a) a.style.animation = 'none';
        }
      };
    }
  }

  const start = function () {
    const component = new Component();
    const vals = component.renderVals();

    ['click', 'mouseenter', 'mouseleave'].forEach(function (evt) {
      document.querySelectorAll('[data-dc-' + evt + ']').forEach(function (el) {
        const fn = vals[el.getAttribute('data-dc-' + evt)];
        if (typeof fn === 'function') el.addEventListener(evt, fn);
      });
    });

    component.componentDidMount();
    window.addEventListener('pagehide', function () {
      component.componentWillUnmount();
    });
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
