// Builds the standalone site (index.html + app.js) from the imported design
// document `Hero Track Star.dc.html`, so the design stays the source of truth.
//
// Three things in the .dc.html are runtime-specific and get translated here:
//   <helmet>...</helmet>        -> the real <head>
//   style-hover="decls"         -> a generated class + a real :hover rule
//   onClick="{{ handler }}"     -> data-dc-click="handler", wired in app.js
//
// The <script data-dc-script> class body is already plain DOM code, so it is
// copied verbatim into app.js under a no-op DCLogic base class.

const fs = require('fs');
const path = require('path');
const enhanceFooter = require('./enhance-footer');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'Hero Track Star.dc.html');

const src = fs.readFileSync(SRC, 'utf8');

const section = (re, what) => {
  const m = re.exec(src);
  if (!m) throw new Error(`could not find ${what} in ${path.basename(SRC)}`);
  return m[1];
};

const helmet = section(/<helmet>([\s\S]*?)<\/helmet>/, '<helmet>');
const dcBody = section(/<x-dc(?:\s[^>]*)?>([\s\S]*)<\/x-dc>/, '<x-dc>');
const logic = section(
  /<script type="text\/x-dc" data-dc-script>([\s\S]*?)<\/script>/,
  'the data-dc-script block'
);

let markup = dcBody.replace(/<helmet>[\s\S]*?<\/helmet>/, '').trim();

// --- style-hover -> real :hover rules -----------------------------------
// Inline styles beat class selectors, so every hover declaration needs
// !important to win. Split on top-level ";" only: values such as box-shadow
// carry commas and parens but never a bare semicolon.
const splitDecls = (decls) => {
  const out = [];
  let depth = 0;
  let buf = '';
  for (const ch of decls) {
    if (ch === '(') depth++;
    else if (ch === ')') depth--;
    if (ch === ';' && depth === 0) {
      out.push(buf);
      buf = '';
    } else buf += ch;
  }
  out.push(buf);
  return out.map((d) => d.trim()).filter(Boolean);
};

const important = (decls) =>
  splitDecls(decls)
    .map((d) => (/!important$/.test(d) ? d : `${d} !important`))
    .join('; ');

const hoverClass = new Map(); // declarations -> class name
markup = markup.replace(/\s+style-hover="([^"]*)"/g, (_, decls) => {
  const key = important(decls);
  if (!hoverClass.has(key)) hoverClass.set(key, `dc-h${hoverClass.size + 1}`);
  return ` class="${hoverClass.get(key)}"`;
});

const hoverCss = [...hoverClass]
  .map(([decls, cls]) => `.${cls}:hover { ${decls}; }`)
  .join('\n');

// --- onEvent="{{ handler }}" -> data-dc-* -------------------------------
const handlers = new Set();
markup = markup.replace(
  /\son([A-Z][a-zA-Z]*)="\{\{\s*([\w$]+)\s*\}\}"/g,
  (_, evt, fn) => {
    handlers.add(fn);
    return ` data-dc-${evt.toLowerCase()}="${fn}"`;
  }
);

// --- footer menu ---------------------------------------------------------
// Adds the chevrons and hooks the mobile footer menu needs. Runs last, so
// it sees the markup after the hover classes and handlers are in place.
markup = enhanceFooter(markup);

// --- sign-in hook --------------------------------------------------------
// Tags the topbar's "Sign in" control so overrides.css and enhancements.js can
// address it directly rather than by position in the nav.
let signIns = 0;
markup = markup.replace(/(<a\s[^>]*?)(>Sign in<\/a>)/g, (_, open, close) => {
  signIns++;
  return `${open} data-signin${close}`;
});
if (signIns !== 1) {
  throw new Error(`build: expected 1 "Sign in" control, found ${signIns}`);
}

// --- emit ----------------------------------------------------------------
const html = `<!DOCTYPE html>
<!-- Generated by build.js from "Hero Track Star.dc.html". Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Track Star — Rate the records you love.</title>
<link rel="icon" href="./favicon.svg" type="image/svg+xml">
${helmet.trim()}
<style>
/* Hover states lifted out of style-hover attributes. */
${hoverCss}
</style>
<!-- Hand-authored corrections, layered last so they win. -->
<link rel="stylesheet" href="./overrides.css">
</head>
<body>
${markup}
<script src="./app.js"></script>
<!-- Hand-authored behaviour, loaded after the generated logic. -->
<script src="./enhancements.js"></script>
</body>
</html>
`;

const app = `// Generated by build.js from "Hero Track Star.dc.html". Do not edit by hand.
// The class body below is copied verbatim from the design document's
// data-dc-script block; only the surrounding wiring is added.
(function () {
  'use strict';

  // The design runtime's base class. Nothing in this component uses it, so an
  // empty base is enough to let the class body run unmodified.
  class DCLogic {}

${logic.trim().replace(/^/gm, '  ')}

  const start = function () {
    const component = new Component();
    const vals = component.renderVals();

    ${[...handlers].length ? `['click', 'mouseenter', 'mouseleave'].forEach(function (evt) {
      document.querySelectorAll('[data-dc-' + evt + ']').forEach(function (el) {
        const fn = vals[el.getAttribute('data-dc-' + evt)];
        if (typeof fn === 'function') el.addEventListener(evt, fn);
      });
    });` : ''}

    component.componentDidMount();
    window.addEventListener('pagehide', function () {
      component.componentWillUnmount();
    });
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
`;

fs.writeFileSync(path.join(ROOT, 'index.html'), html, 'utf8');
fs.writeFileSync(path.join(ROOT, 'app.js'), app, 'utf8');

console.log(
  `index.html  ${html.length} bytes  (${hoverClass.size} hover rules, ` +
    `${handlers.size} handlers: ${[...handlers].join(', ')})`
);
console.log(`app.js      ${app.length} bytes`);
